version: '3'
services:
  foo:
    build:
      context: .
      args:
        - LOCAL_PORT=$FOO_PORT
        - REMOTE_PORT=$BAR_PORT
        - REMOTE_NAME=bar
        - WAIT=$WAIT
    container_name: foo
    restart: always
    ports:
     - "$FOO_PORT:$FOO_PORT"
  bar:
    build:
      context: .
      args:
        - LOCAL_PORT=$BAR_PORT
        - REMOTE_PORT=$FOO_PORT
        - REMOTE_NAME=foo
        - WAIT=$WAIT
    container_name: bar
    restart: always
    ports:
      - "$BAR_PORT:$BAR_PORT"
    depends_on:
      - foo
