version: '3'
services:
  foo:
    build:
      context: .
      args:
        - LOCAL_PORT=$FOO_PORT
        - REMOTE_PORT=$BAR_PORT
        - REMOTE_NAME=bar
    container_name: foo
    restart: always
    ports:
     - "$FOO_PORT:$FOO_PORT"
    environment:
      - LOCAL_PORT=$FOO_PORT
      - REMOTE_PORT=$BAR_PORT
      - REMOTE_NAME=bar
      - WAIT=$WAIT
    networks:
      main:
        aliases:
          - foo
  bar:
    build:
      context: .
      args:
        - LOCAL_PORT=$BAR_PORT
        - REMOTE_PORT=$FOO_PORT
        - REMOTE_NAME=foo
    container_name: bar
    restart: always
    ports:
      - "$BAR_PORT:$BAR_PORT"
    environment:
      - LOCAL_PORT=$BAR_PORT
      - REMOTE_PORT=$FOO_PORT
      - REMOTE_NAME=foo
      - WAIT=$WAIT
    networks:
      main:
        aliases:
          - bar
    depends_on:
      - foo
networks:
  main: