FROM node:14.15.3

ARG LOCAL_PORT
ARG REMOTE_PORT
ARG REMOTE_NAME
ARG WAIT=1500

EXPOSE $LOCAL_PORT

WORKDIR /usr/src/app

COPY app.c .

RUN cc -D WAIT=$WAIT -D LOCAL_PORT=$LOCAL_PORT -D REMOTE_PORT=$REMOTE_PORT -D REMOTE_NAME=\"$REMOTE_NAME\" -o app app.c -lc -lpthread

CMD ["./app"]
