FROM node:14.15.3

ARG LOCAL_PORT
ARG REMOTE_PORT
ARG REMOTE_NAME
ARG WAIT=1500

ENV LOCAL_PORT=$LOCAL_PORT
ENV REMOTE_PORT=$REMOTE_PORT
ENV REMOTE_NAME=$REMOTE_NAME
ENV WAIT=$WAIT

EXPOSE $LOCAL_PORT

WORKDIR /usr/src/app
COPY package*json ./

RUN npm install --production --no-optional
COPY app.js .
CMD ["node", "app.js"]